# Generated by Django 4.2.6 on 2024-02-19 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='validUntil',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 9, 41, 39, 848754, tzinfo=datetime.timezone.utc)),
        ),
    ]
