# Generated by Django 4.2.6 on 2024-01-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
