# Generated by Django 4.2.6 on 2024-02-19 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_user_emailverified_alter_otp_validuntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='validUntil',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 10, 20, 43, 391939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
