# Generated by Django 4.2.6 on 2024-01-29 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='validUntil',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 10, 11, 40, 293553, tzinfo=datetime.timezone.utc)),
        ),
    ]
