# Generated by Django 4.2.6 on 2024-01-29 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_alter_otp_validuntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='validUntil',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 10, 12, 23, 793369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usualloginlocation',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usualloginlocation',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
